### ISSUE TITLE
Getting AuthenticationException when calling ssl.AuthenticateAsClient(host);

### ISSUE THREAD

**Issue by andersmi10** [jimm98y/SharpAndroidTV#1]
Hi Lukas

Hope you can help here.
I am getting an AuthenticationException with this innerexception
The message received was unexpected or badly formatted.

When calling ssl.AuthenticateAsClient(host) here.
![image](https://github.com/jimm98y/AndroidTVAPI/assets/35544287/82126917-507b-4e30-8994-163c30fe2737)

I am getting the pairing code on the TV when the SendPairingMessageAsync method is called later, but I am missing the certificate from the GetPublicCertificate method to complete the pairing.

Do you have any ideas?

Thanks
Anders

**Comment by andersmi10** [comment]
Tv is a Nokia QN70GV315ISW with android RTM6.230109.138

**Comment by jimm98y** [comment]
Which OS and .NET version are you running on? Having Wireshark log of the communication would help to diagnose the problem. I could only try this on TCL TVs, unfortunately.

**Comment by andersmi10** [comment]
It is a .Net core 3 application, the OS is Android TV 11.

I will try to use Wireshark, what am I looking for?

I just need to detect if the TV is turned on, do you know if there is a easier way to do this?

Thanks again

**Comment by jimm98y** [comment]
In Wireshark, you are looking for the IP address of your TV and there should be a new TLS connection from your PC to the TV. Probably you'll see some errors as well, with a bit more detail on what's going on. You can filter using "ip.addr == <your TV's IP Address>".

As for checking if the TV is turned on, I'd probably try to periodically check my router - it has a list of active devices that you can request over REST API. Using this library is probably an overkill if you do not want to control the TV. In theory (I haven't tried it) while the TV is off you should not be able to connect - then you can periodically try opening a TCP connection to TV's port 6466 and if it fails then the TV is off, if it succeeds the TV is on and you can immediately close the connection.

**Comment by andersmi10** [comment]
Just tried to connect to the TV with a TCP connection when it is turned off and it doesn't connect and accepts when turned off, great solution! Can't believe I didn't think of that, you are a life saver, needs it to power up my NAS when I turn on the TV, I then have a Raspberry PI to check if the TV turns on. Once again thanks!

**Comment by jimm98y** [comment]
I'm glad I could help! I'm closing this issue then.
