### ISSUE TITLE
Authentication failed 

### ISSUE THREAD

**Issue by michealdemus** [jimm98y/SharpAndroidTV#3]
Hello, I have a problem with the following error: System.IO.IOException: 'Authentication failed because the remote party has closed the transport stream.' in line this._networkStream.AuthenticateAsClient(
    GetIP(),
    new X509CertificateCollection()
    {
        this._clientCertificate
    },
    SslProtocols.Tls12, // required to make a successful connection
    false);
Do you have an idea how to fix it ?
I want to connect it to Google Chromecast 4.0

**Comment by jimm98y** [comment]
Could you please send me a Wireshark log of the connection? I don't have Google Chromecast, so I can't test it. It's quite possible Google has changed something in the protocol. Newer OS might just need TLS 1.3 - I based this off of my TCL TV which at the time I wrote it required TLS 1.2.

**Comment by michealdemus** [comment]
It uses TCP

**Comment by michealdemus** [comment]
It uses tls 1.3

**Comment by jimm98y** [comment]
netstandard2.0 does not support TLS1.3, but you can use it in a NET8 application that does support it. I've added a new ctor that allows you to set that enum to SslProtocols.Tls13 as long as you are using NET Core that supports it. There is a new nuget 0.0.3 with this fix, please let me know if it works.
